spring:
  application:
    name: job-worker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ag_platform?currentSchema=job_work
    username: postgres
    password: '1234'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 18082

logging:
  config: classpath:logback-spring.xml

rocketmq:
  name-server: localhost:9876
